### PR TITLE
Add python library installation for pwndbg

### PR DESCRIPTION
**Pull request by moryyi**
Add a requirements.txt for pwndbg to make sure gdb-pwndbg works correctly after the whole installation if the user haven't installed pwndbg before.

### CODE REVIEW

**Comment by apogiatzis** [comment]
Hey there! Thanks for your contribution. Correct me if I am wrong... but isn't that included in the pwndbg setup script anyway? https://github.com/pwndbg/pwndbg/blob/dev/setup.sh#L154

**Comment by moryyi** [comment]
Hi! I think I may check it again because I have installed this with "./install.sh" for several times, and each time only pwndbg doesn't seem to work properly and the requirements.txt of pwndbg doesn't be installed correctly. It works only if I manually pip install them. Anyway I will check this tomorrow. Thank you very much.

**Comment by moryyi** [comment]
Ok I have tried to reproduce and I found it works very desent right now. I check and compare the pwndbg's latest "setup.sh" with previous version and find that pwndbg has fixed the "install_apt()", saying that the previous settings may break ubuntu 20.04. I think I should make checks more carefully next time. Anyway thank you very much for your reply.

**Comment by apogiatzis** [comment]
No problem thakns for looking into it! Will close this now :)

**Pull request closed without merging**
